FROM composer:2.7 AS deps
WORKDIR /app
COPY . .
RUN composer install --no-dev --no-scripts --ignore-platform-reqs --prefer-dist

FROM php:8.2-fpm
RUN apt-get update && apt-get install -y --no-install-recommends libpng-dev libzip-dev libfreetype6-dev libjpeg62-turbo-dev libwebp-dev unzip mariadb-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install mysqli gd zip \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /var/www/html
COPY --from=deps /app ./
RUN chown -R www-data:www-data /var/www/html
CMD ["php-fpm"]
